/*	****************************************************************
	**  This program is provided to the professors and students   **
	**  using "Computer Science: A Structured Approach Using C,   **
	**  Second Edition." All reprints in any form must cite this  **
	**  copyright.                                                **
    **                                                            **
	**  Copyright(c) 2001 by Brooks/Cole                          **
	**  A division of Thomson Learning                            **
	****************************************************************
*/

/*	This include file contains the link list functions
	developed in Chapter 14.
	   Written by: 
	   Date:  
*/
#ifndef LINK_HEADER
   #define LINK_HEADER

/*	Include Files for Functions        */
#include "P14-02.c"      /* Delete     */
#include "P14-01.c"      /* Insert     */
#include "P14-03.c"      /* Seek Node  */
#include "P14-04.c"      /* Search     */
#include "P14-05.c"      /* Print List */
#include "P14-06.c"      /* Average    */
#include "P14-07.c"      /* buildChron */
#include "P14-08.c"      /* buildSeq   */
#include "P14-09.c"      /* deleteChron*/
#include "p14-12.c"      /* append     */
#endif
